version: '3.4'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: lanchoneteApp
      POSTGRES_PASSWORD: Unica@123
      POSTGRES_DB: dbLanchonete
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: douglasferreiramiyamoto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Unica@123
    ports:
      - "5050:80"
    networks:
      - backend

  lanchoneteapi:
    image: ${DOCKER_REGISTRY-}productsapi   
    container_name: lanchoneteapi
    build:
      context: .
      dockerfile: LanchoneteApi/Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=dbLanchonete;Username=lanchoneteApp;Password=Unica@123
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata: