apiVersion: v1
kind: Service
metadata:
  name: lanchoneteapi-service
spec:
  type: NodePort
  selector:
    app: lanchoneteapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  