apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchoneteapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchoneteapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lanchoneteapi
    spec:
      containers:
      - name: lanchoneteapi
        image: dmiyamoto86/lanchoneteapi:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20  
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=${DB_HOST};Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
        - name: DB_HOST
          value: "terraform-20241217144920197700000001.chqo2oe6wh35.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "dbLanchonete"
        - name: DB_USER
          value: "lanchoneteApp"  
        - name: DB_PASSWORD
          value: "Unica123"
