name: Deploy API

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, and Deploy API
    runs-on: ubuntu-latest

    env:
      EKS_CLUSTER_NAME: lanchonete-cluster
      DOCKER_IMAGE_NAME: dmiyamoto86/lanchoneteapi
      DOCKER_IMAGE_TAG: latest
      AWS_REGION: us-east-1

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.121.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Update kubeconfig using eksctl
      run: |
        eksctl utils associate-iam-oidc-provider --region $AWS_REGION --cluster $EKS_CLUSTER_NAME --approve
        eksctl create iamserviceaccount \
          --region $AWS_REGION \
          --name eks-service-account \
          --namespace default \
          --cluster $EKS_CLUSTER_NAME \
          --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy \
          --approve

    - name: Build and Push Docker Image
      run: |
        docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f LanchoneteApi/Dockerfile .
        docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

    - name: Deploy to Kubernetes using eksctl
      run: |
        eksctl create deployment \
          --name lanchoneteapi \
          --image $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG \
          --cluster $EKS_CLUSTER_NAME \
          --region $AWS_REGION \
          --kubeconfig ~/.kube/config
