name: Deploy API

on:
  pull_request:
    types:
      - closed
    branches:
      - main  

jobs:
  deploy:
    name: Build, Push, and Deploy API
    runs-on: ubuntu-latest

    env:
      EKS_CLUSTER_NAME: lanchonete-cluster
      DOCKER_IMAGE_NAME: dmiyamoto86/lanchoneteapi
      DOCKER_IMAGE_TAG: latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig for EKS
      run: |
        aws eks --region us-east-1 update-kubeconfig --name $EKS_CLUSTER_NAME

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f LanchoneteApi/Dockerfile .
        docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml --validate=false
