name: Deploy API

on:
  pull_request:
    types:
      - closed
    branches:
      - main  

jobs:
  deploy:
    name: Build, Push, and Deploy API
    runs-on: ubuntu-latest

    env:
      EKS_CLUSTER_NAME: lanchonete-cluster
      DOCKER_IMAGE_NAME: dmiyamoto86/lanchoneteapi
      DOCKER_IMAGE_TAG: latest
      AWS_REGION: us-east-1

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::194722421948:role/lanchonete-cluster-cluster-20241217214657016100000002
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHubActionsSession
        id-token: true  # Habilita a autenticação via OIDC
        
    - name: Update kubeconfig for EKS
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f LanchoneteApi/Dockerfile .
        docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml --validate=false
